//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentZone
    {
        public long AssessmentZoneId { get; set; }
        public Nullable<int> DiciplinePresence { get; set; }
        public Nullable<int> FirstSession { get; set; }
        public Nullable<int> SecondSession { get; set; }
        public Nullable<int> ThirdSession { get; set; }
        public Nullable<int> CleanlinessOfZone { get; set; }
        public Nullable<int> CompletenessOfTeam { get; set; }
        public Nullable<int> DataOfGarbage { get; set; }
        public Nullable<long> EmployeeId { get; set; }
        public string TypeZone { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
