//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coordinator
    {
        public long CoordinatorId { get; set; }
        public Nullable<int> PercentOfPresence { get; set; }
        public Nullable<int> PercentOfReport { get; set; }
        public Nullable<int> PercentOfCompletion { get; set; }
        public Nullable<int> PercentOfSatisfaction { get; set; }
        public Nullable<int> Cleanliness { get; set; }
        public Nullable<int> DataOfGarbage { get; set; }
        public Nullable<long> EmployeeId { get; set; }
        public Nullable<System.DateTime> DateOfAssessment { get; set; }
    }
}
