//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drainage
    {
        public long DrainageId { get; set; }
        public Nullable<int> Dicipline { get; set; }
        public Nullable<int> Completeness { get; set; }
        public Nullable<int> Cleanliness { get; set; }
        public Nullable<int> Sediment { get; set; }
        public Nullable<int> Weed { get; set; }
        public Nullable<long> PresenceId { get; set; }
    
        public virtual Presence Presence { get; set; }
    }
}
