//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.AssessmentZones = new HashSet<AssessmentZone>();
            this.Leaves = new HashSet<Leave>();
            this.Presences = new HashSet<Presence>();
            this.Users = new HashSet<User>();
        }
    
        public long EmployeeId { get; set; }
        public string EmployeeNumber { get; set; }
        public Nullable<System.DateTime> FirstContract { get; set; }
        public Nullable<System.DateTime> LastContract { get; set; }
        public string LocationContract { get; set; }
        public Nullable<long> PersonId { get; set; }
        public Nullable<long> RoleId { get; set; }
        public Nullable<long> RegionId { get; set; }
        public Nullable<long> ZoneId { get; set; }
        public string Bank { get; set; }
        public string Shift { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssessmentZone> AssessmentZones { get; set; }
        public virtual Person Person { get; set; }
        public virtual Region Region { get; set; }
        public virtual Zone Zone { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Leave> Leaves { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Presence> Presences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
        public virtual Role Role { get; set; }
    }
}
