//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Garbage
    {
        public long GerbageId { get; set; }
        public Nullable<int> Dicipline { get; set; }
        public Nullable<int> TPS { get; set; }
        public Nullable<int> Separation { get; set; }
        public Nullable<int> Calculation { get; set; }
        public Nullable<int> VolumeOfOrganic { get; set; }
        public Nullable<int> VolumeOfAnorganic { get; set; }
        public Nullable<long> PresenceId { get; set; }
    
        public virtual Presence Presence { get; set; }
    }
}
