//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interview
    {
        public long InterviewId { get; set; }
        public string Interviewer { get; set; }
        public string Place { get; set; }
        public Nullable<System.DateTime> DateOfInterview { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
    }
}
