//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public long ItemId { get; set; }
        public string ItemName { get; set; }
        public byte[] ItemPhoto { get; set; }
        public Nullable<int> ItemQty { get; set; }
        public string Note { get; set; }
        public Nullable<long> CategoryId { get; set; }
        public string ItemCode { get; set; }
    }
}
