//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person()
        {
            this.Employees = new HashSet<Employee>();
        }
    
        public long PersonId { get; set; }
        public string PersonName { get; set; }
        public string PlaceOfBirth { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string LastDegree { get; set; }
        public string PreviousJob { get; set; }
        public string NameOfCouple { get; set; }
        public string JobOfCouple { get; set; }
        public byte[] Photo { get; set; }
        public byte[] KTP { get; set; }
        public byte[] Sertificate { get; set; }
        public byte[] AppLetter { get; set; }
        public string Jobdesk { get; set; }
        public Nullable<int> TotalChild { get; set; }
        public string Email { get; set; }
        public string NIK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
