//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Presence
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Presence()
        {
            this.Drainages = new HashSet<Drainage>();
            this.Garbages = new HashSet<Garbage>();
            this.HeadOfZones = new HashSet<HeadOfZone>();
            this.Sweepers = new HashSet<Sweeper>();
        }
    
        public long PresenceId { get; set; }
        public byte[] LivePhoto { get; set; }
        public string Coordinate { get; set; }
        public Nullable<System.DateTime> DateOfPresence { get; set; }
        public string PresenceStatus { get; set; }
        public Nullable<long> EmployeeId { get; set; }
        public string Location { get; set; }
        public Nullable<int> Counter { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Drainage> Drainages { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Garbage> Garbages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HeadOfZone> HeadOfZones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sweeper> Sweepers { get; set; }
    }
}
