//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Submission
    {
        public long SubmissionId { get; set; }
        public Nullable<long> ItemId { get; set; }
        public Nullable<System.DateTime> DateOfSubmission { get; set; }
        public Nullable<int> Qty { get; set; }
        public string Status { get; set; }
        public string Desc { get; set; }
        public Nullable<long> SubmissionUser { get; set; }
        public byte[] Document { get; set; }
    }
}
