//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sweeper
    {
        public long SweeperId { get; set; }
        public Nullable<int> Dicipline { get; set; }
        public Nullable<int> Completeness { get; set; }
        public Nullable<int> Road { get; set; }
        public Nullable<int> Sidewalk { get; set; }
        public Nullable<int> WaterRope { get; set; }
        public Nullable<int> RoadMedian { get; set; }
        public Nullable<long> PresenceId { get; set; }
    
        public virtual Presence Presence { get; set; }
    }
}
