//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class vPresenceResume
    {
        public long Id { get; set; }
        public string LocationContract { get; set; }
        public Nullable<long> EmployeeId { get; set; }
        public string PersonName { get; set; }
        public string EmployeeNumber { get; set; }
        public string RoleName { get; set; }
        public Nullable<int> Absence { get; set; }
        public Nullable<int> Leave { get; set; }
        public Nullable<int> PresenceTotal { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<int> Presence { get; set; }
        public string ZoneName { get; set; }
        public string RegionName { get; set; }
        public string Shift { get; set; }
    }
}
